### ISSUE TITLE
cannot update deadline

### ISSUE THREAD

**Issue by pacomski** [pierremarc/pearls#2]
- set a deadline (eg : 30/04/2020)
- change the deadline (30/04/2021)

--> it seems that the new deadline is not taken into account..

**Comment by pacomski** [comment]
update : it seems that it cannot record a deadline > 2020

**Comment by pacomski** [comment]
neither < 2020 ;)

**Comment by pierremarc** [comment]
Well, it's more that the date format is either `YYYY-MM-DD`, `DD-MM-YYYY` or `DD-MM` (year being infered to be current year) and that failing to parse date triggered the `complete_now` branch which assumes completion date to be now.

Yes, this need to be better documented :) 

[EDIT] Just re-reading, it might be a parsing date issue, but not related to `!complete`, my bad, will look into it

**Comment by pierremarc** [comment]
I double checked and actually got no problem to set a deadline and edit it afterward. I guess it was a format problem. I updated the help message for this. Closing
